TEST_CLIENT_SERVICE_HOST = '127.0.0.1'
TEST_CLIENT_SERVICE_PORT = '5000'
TEST_CLIENT_SERVICE_ADDRESS = '{host}:{port}'.format(host=TEST_CLIENT_SERVICE_HOST, port=TEST_CLIENT_SERVICE_PORT)

TEST_CORE_SERVICE_HOST = '127.0.0.1'
TEST_CORE_SERVICE_PORT = '5001'
TEST_CORE_SERVICE_ADDRESS = '{host}:{port}'.format(host=TEST_CORE_SERVICE_HOST, port=TEST_CORE_SERVICE_PORT)