# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prime_proto/prime_finder_core/get_largest_prime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='prime_proto/prime_finder_core/get_largest_prime.proto',
  package='prime_finder_core.get_largest_prime',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n5prime_proto/prime_finder_core/get_largest_prime.proto\x12#prime_finder_core.get_largest_prime\"\x1d\n\x0cInputRequest\x12\r\n\x05value\x18\x01 \x01(\x04\"I\n\x17UnsignedIntegerResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x04\x32\x99\x01\n\x12LargestPrimeFinder\x12\x82\x01\n\x0fGetLargestPrime\x12\x31.prime_finder_core.get_largest_prime.InputRequest\x1a<.prime_finder_core.get_largest_prime.UnsignedIntegerResponseb\x06proto3'
)




_INPUTREQUEST = _descriptor.Descriptor(
  name='InputRequest',
  full_name='prime_finder_core.get_largest_prime.InputRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='prime_finder_core.get_largest_prime.InputRequest.value', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=123,
)


_UNSIGNEDINTEGERRESPONSE = _descriptor.Descriptor(
  name='UnsignedIntegerResponse',
  full_name='prime_finder_core.get_largest_prime.UnsignedIntegerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='prime_finder_core.get_largest_prime.UnsignedIntegerResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='prime_finder_core.get_largest_prime.UnsignedIntegerResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='prime_finder_core.get_largest_prime.UnsignedIntegerResponse.value', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=198,
)

DESCRIPTOR.message_types_by_name['InputRequest'] = _INPUTREQUEST
DESCRIPTOR.message_types_by_name['UnsignedIntegerResponse'] = _UNSIGNEDINTEGERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputRequest = _reflection.GeneratedProtocolMessageType('InputRequest', (_message.Message,), {
  'DESCRIPTOR' : _INPUTREQUEST,
  '__module__' : 'prime_proto.prime_finder_core.get_largest_prime_pb2'
  # @@protoc_insertion_point(class_scope:prime_finder_core.get_largest_prime.InputRequest)
  })
_sym_db.RegisterMessage(InputRequest)

UnsignedIntegerResponse = _reflection.GeneratedProtocolMessageType('UnsignedIntegerResponse', (_message.Message,), {
  'DESCRIPTOR' : _UNSIGNEDINTEGERRESPONSE,
  '__module__' : 'prime_proto.prime_finder_core.get_largest_prime_pb2'
  # @@protoc_insertion_point(class_scope:prime_finder_core.get_largest_prime.UnsignedIntegerResponse)
  })
_sym_db.RegisterMessage(UnsignedIntegerResponse)



_LARGESTPRIMEFINDER = _descriptor.ServiceDescriptor(
  name='LargestPrimeFinder',
  full_name='prime_finder_core.get_largest_prime.LargestPrimeFinder',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=201,
  serialized_end=354,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLargestPrime',
    full_name='prime_finder_core.get_largest_prime.LargestPrimeFinder.GetLargestPrime',
    index=0,
    containing_service=None,
    input_type=_INPUTREQUEST,
    output_type=_UNSIGNEDINTEGERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LARGESTPRIMEFINDER)

DESCRIPTOR.services_by_name['LargestPrimeFinder'] = _LARGESTPRIMEFINDER

# @@protoc_insertion_point(module_scope)
